openapi: 3.0.3
info:
  title: KMS KNPKI
  description: Api Specification for KMS KNPKI
  version: 1.0.0
  contact:
    name: Muhammad Naufal
    email: muhammadnaufaall@gmail.com
    url: https://linkedin.com/in/mhmmdnaufall
servers:
  - url: https://www.knpkid.org/
    description: KNPKI Server
tags:
  - name: Auth
    description: For authentication matters


paths:

  /api/admin:
    get:
      summary: Get Current Admin Account
      tags:
        - Admin
      security:
        - BearerToken: []
      responses:
        200:
          description: Success get Current Admin Account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data:
                  username: mhmmdnaufal
                  name: Naufal
                  image: jfvnrhofhishvf3fi1rf31y4rt9wurofurjqi]igtgi-2jgu4...
                errors: null
                paging: null
        401:
          $ref: "#/components/responses/401"

    post:
      summary: Register Admin
      tags:
        - Admin
      security:
        - CsrfToken: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/RegisterAdminRequest"
      responses:
        200:
          description: Success create admin account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponseString"
              example:
                data: OK
                errors: null
                paging: null

        400:
          description: Wrong format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"

        403:
          $ref: "#/components/responses/403"

  /api/auth/login:
    post:
      summary: Admin login
      tags:
        - Auth
      security:
        - CsrfToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginAdminRequest"
      responses:
        200:
          description: Success login admin
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data:
                  token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwNzQ3NzEwMCwiZXhwIjoxNzA3NDgwNzAwfQ.I9imemHoNVQiGYAeN8C5_-_1ETTFXOtu_Vg-tAbkkudEi1HiFMqxNOwmt1Ax3ke7rCqiTgh2v96AOaHfRvnzdw
                errors: null
                paging: null

        400:
          description: Wrong Format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              examples:
                blank username:
                  description: username blank error
                  value:
                    data: null
                    errors: "username: must not be blank"
                    paging: null
                blank password:
                  description: password blank error
                  value:
                    data: null
                    errors: "password: size must be between 5 and 30, password: must not be blank"
                    paging: null
                blank username & password:
                  description: username & password blank error
                  value:
                    data: null
                    errors: "password: size must be between 5 and 30, password: must not be blank, username: must not be blank"
                    paging: null
                username length:
                  description: username is not compatible with size format
                  value:
                    data: null
                    errors: "username: size must be between 0 and 20"
                    paging: null
                password length:
                  description: password is not compatible with size format
                  value:
                    data: null
                    errors: "password: size must be between 5 and 30"
                    paging: null
                username & password length:
                  description: username and password is not compatible with size format
                  value:
                    data: null
                    errors: "password: size must be between 5 and 30, username: size must be between 0 and 20"
                    paging: null

        401:
          description: Failed authorizing account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data: null
                errors: Username or password wrong
                paging: null

  /api/auth/logout:
    delete:
      summary: Admin logout
      tags:
        - Auth
      security:
        - BearerToken: []
        - CsrfToken: []
      responses:
        204:
          description: Success logout admin
        401:
          $ref: "#/components/responses/401"

  /api/auth/csrf:
    get:
      summary: Get CSRF token
      tags:
        - Auth
      responses:
        200:
          description: Success get CSRF Token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data:
                  parameterName: _csrf
                  token: AFrfI_NNzqELpggF6jjV2x5voCvXkDyKQlzaK2zsO1b1VZfeYmK8G8srqsAmw2kwiRXh6ioMjUmy9QyncWXpHlTUDGGRY_W6
                  headerName: X-CSRF-TOKEN
                errors: null
                paging: null

        401:
          $ref: "#/components/responses/401"



  /api/articles:
    get:
      summary: Get All Existing Article OR Search Article
      tags:
        - Article
      parameters:
        - name: search
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 12
      responses:
        200:
          description: Success get all existing Article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponseListOnlyArticleResponse"
              example:
                data:
                  - id: 1f24face-9475-44b4-965a-5b811e997252
                    title: Pengaruh BBM Naik 100% kepada Keluarga
                    createdAt: '2024-02-07 16:23:16'
                    updatedAt: '2024-02-07 16:23:16'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 607e7f00-84df-4433-b598-6ce8c5d943bd
                    title: Pengaruh BBM Naik 100% kepada Keluarga
                    createdAt: '2024-02-06 23:55:52'
                    updatedAt: '2024-02-06 23:55:52'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 8c751e8c-fca5-43f5-bc9a-970b611f8e4f
                    title: this is judul
                    createdAt: '2024-02-06 23:27:56'
                    updatedAt: '2024-02-06 23:27:56'
                    body: body
                    teaser: teaser baru ini
                    coverImage:
                  - id: 6c153e83-5e7b-41fc-a8e5-9d2bb4259d0a
                    title: Ini Judul
                    createdAt: '2024-02-06 01:41:39'
                    updatedAt: '2024-02-06 01:41:39'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEoHBw7nZhZY0cKA..."
                  - id: 2140456f-e0ad-4b7f-83aa-8a448e20d6b1
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:32'
                    updatedAt: '2024-02-06 01:40:32'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 42e918b5-130e-4434-9ddb-385e1f96923c
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:31'
                    updatedAt: '2024-02-06 01:40:31'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 8eda744b-cb15-445d-b711-9484be66f53a
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:30'
                    updatedAt: '2024-02-06 01:40:30'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: f769e575-29a9-4e51-975b-52af1472bdd6
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:29'
                    updatedAt: '2024-02-06 01:40:29'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 95a0c12e-e787-4393-9b55-6ea8b56405a6
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:28'
                    updatedAt: '2024-02-06 01:40:28'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 6170a8a6-62eb-490e-a3c8-cded3f2b6242
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:26'
                    updatedAt: '2024-02-06 01:40:26'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 6da739a0-3294-422a-8cce-83238858b7e5
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:25'
                    updatedAt: '2024-02-06 01:40:25'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: c44702ba-e47d-426d-91c5-62b0d8f0c5e6
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:24'
                    updatedAt: '2024-02-06 01:40:24'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                errors: null
                paging:
                  currentPage: 0
                  totalPage: 5
                  size: 12

    post:
      summary: Create Article
      description: For create new article. only for logged-in account (admin)
      tags:
        - Article
      security:
        - BearerToken: []
        - CsrfToken: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CreateArticleRequest"
      responses:
        201:
          description: Success create new Article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponseString"
              example:
                data: article created with id `02904f4b-6260-44ad-91a0-caa3d792d245`
                errors: null
                paging: null
        401:
          $ref: "#/components/responses/401"

        400:
          description: Wrong format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              examples:
                blank title:
                  description: "title can't be blank"
                  value:
                    data: "title: must not be blank"
                    errors: null
                    paging: null


        403:
          $ref: "#/components/responses/403"

  /api/articles/{articleId}:
    get:
      summary: View specified article
      tags:
        - Article
      parameters:
        - name: articleId
          in: path
          required: true
          schema:
            type: string
          description: Put the `id` of the article you want to view
          example: 5c020359-a6db-42ba-9285-772e739f2620
      responses:
        200:
          description: Viewing specified article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponseArticleResponse"
              example:
                data:
                  id: f9467a1b-bc25-45f5-85a1-0b3cdb5f60b1
                  title: Pengaruh BBM Naik 100% kepada Keluarga
                  createdAt: 2024-03-01 15:00:00
                  updatedAt: 2024-03-01 15:00:00
                  body: Ini merupakan tubuh dari tulisan artikel
                  teaser: Artikel ini membicarakan definisi artikel
                  tags:
                    - id: bbm-naik
                      name: bbm naik
                    - id: pengaruh-bbm
                      name: pengaruh bbm
                    - id: bbm
                      name: bbm
                  admin:
                    username: admin
                    name: Admin
                    image: fyecy2ry43ycr3n9hfrhn9vnaofhafafp3]ptr432u9v8qq...
                  coverImage: sdfh2349ny49fynt9348yw9crfhohvfn2hopitghno...
                  images:
                    - id: 26f7b011-11be-49c1-aa23-b96f914a2fd8
                      image: aiosdoiasowq90-nu0fuhrfn0-u[paotjvpw...
                    - id: c67f3d86-67b9-4936-9556-aa2d53eaab89
                      image: saodihy924hryahnsbflhnt3b1n[h02937380hgdj...
                    - id: f18b1840-0be5-40bb-9364-b067cda5c5ea
                      image: z;ufv3496thvobhneqiohgn9qnhgobhohnzj...
                errors: null
                paging: null

        404:
          description: Article is not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data: null
                errors: Article is not found
                paging: null

    put:
      summary: Update article
      tags:
        - Article
      security:
        - BearerToken: []
        - CsrfToken: []
      parameters:
        - name: articleId
          in: path
          required: true
          schema:
            type: string
          description: Put the `id` of the article you want to update
          example: 5c020359-a6db-42ba-9285-772e739f2620
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UpdateArticleRequest"
      responses:
        200:
          description: Update Article Successed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data:
                  id: 5c020359-a6db-42ba-9285-772e739f2620
                  title: Ini Judul
                  createdAt: 2024-03-01 15:00:00
                  updatedAt: 2024-03-02 10:32:56
                  coverImage: fyecy2ry43ycr3n9hfrhn9vnaofhafafp3]ptr432u9v8qq
                  body: Article merupakan karya tulis lengkap, misalnya laporan berita atau esai dalam majalah, surat kabar dan sebagainya
                  teaser: Artikel ini membicarakan definisi artikel
                  tags:
                    - Article
                    - Artikel
                    - Definition
                    - Karya Tulis
                  images:
                    - ufrun994832unr9asfjajfvjpjbpjf[jf]FFK0[fbk0aifpoi9-rinbt
                    - aisodjoijnvur0-vUAVHFNH4392upfjFEJNP[RJPFEJSRa5ybqhww
                    - ohjnf08u4n0t4u30rajfvapjevjeqjtqjbatq4t632tq4wt4tn
                    - 5923ybn9yahbtoghosdhgoabjtogj502ajvfjojnbjj09ut
                errors: null
                paging: null
        401:
          $ref: "#/components/responses/401"

        403:
          $ref: "#/components/responses/403"

        403a:
          description: admin trying to update article on another admins article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data: null
                errors: this article belongs to someone else
                paging: null


    delete:
      summary: Delete Article
      description: For deleting article. only for logged-in account (admin)
      tags:
        - Article
      security:
        - BearerToken: []
        - CsrfToken: []
      parameters:
        - name: articleId
          in: path
          required: true
          schema:
            type: string
          description: Put the `id` of the article you want to delete
          example: 5c020359-a6db-42ba-9285-772e739f2620
      responses:
        204:
          description: Success Delete Article

        401:
          $ref: "#/components/responses/401"

        403:
          $ref: "#/components/responses/403"

        403a:
          description: admin trying to delete article on another admins article
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data: null
                errors: this article belongs to someone else
                paging: null

        404:
          description: Article is not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data: null
                errors: Article with id `5c020359-a6db-42ba-9285-772e739f2620` is not found
                paging: null



  /api/tags/{tagId}/articles:
    get:
      summary: Get all related article with given tag
      tags:
        - Article
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
          description: Put the tags id you want to search
          example: bbm-naik
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 12

      responses:
        200:
          description: Success get related article with given tags
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data:
                  - id: 1f24face-9475-44b4-965a-5b811e997252
                    title: Pengaruh BBM Naik 100% kepada Keluarga
                    createdAt: '2024-02-07 16:23:16'
                    updatedAt: '2024-02-07 16:23:16'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 607e7f00-84df-4433-b598-6ce8c5d943bd
                    title: Pengaruh BBM Naik 100% kepada Keluarga
                    createdAt: '2024-02-06 23:55:52'
                    updatedAt: '2024-02-06 23:55:52'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 8c751e8c-fca5-43f5-bc9a-970b611f8e4f
                    title: this is judul
                    createdAt: '2024-02-06 23:27:56'
                    updatedAt: '2024-02-06 23:27:56'
                    body: body
                    teaser: teaser baru ini
                    coverImage:
                  - id: 6c153e83-5e7b-41fc-a8e5-9d2bb4259d0a
                    title: Ini Judul
                    createdAt: '2024-02-06 01:41:39'
                    updatedAt: '2024-02-06 01:41:39'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEoHBw7nZhZY0cKA..."
                  - id: 2140456f-e0ad-4b7f-83aa-8a448e20d6b1
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:32'
                    updatedAt: '2024-02-06 01:40:32'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 42e918b5-130e-4434-9ddb-385e1f96923c
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:31'
                    updatedAt: '2024-02-06 01:40:31'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 8eda744b-cb15-445d-b711-9484be66f53a
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:30'
                    updatedAt: '2024-02-06 01:40:30'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: f769e575-29a9-4e51-975b-52af1472bdd6
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:29'
                    updatedAt: '2024-02-06 01:40:29'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 95a0c12e-e787-4393-9b55-6ea8b56405a6
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:28'
                    updatedAt: '2024-02-06 01:40:28'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 6170a8a6-62eb-490e-a3c8-cded3f2b6242
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:26'
                    updatedAt: '2024-02-06 01:40:26'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: 6da739a0-3294-422a-8cce-83238858b7e5
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:25'
                    updatedAt: '2024-02-06 01:40:25'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                  - id: c44702ba-e47d-426d-91c5-62b0d8f0c5e6
                    title: Ini Judul
                    createdAt: '2024-02-06 01:40:24'
                    updatedAt: '2024-02-06 01:40:24'
                    body: Ini merupakan tubuh dari tulisan artikel
                    teaser: Kerangka Artikel
                    coverImage: null
                errors: null
                paging:
                  currentPage: 0
                  totalPage: 5
                  size: 12

        404:
          description: Article with specified tag is not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebResponse"
              example:
                data: null
                errors: Article with tag 'orang-tua' is not found
                paging: null

components:

  securitySchemes:
    BearerToken:
      description: Put JWT Token with format "Bearer `token`"
      type: apiKey
      in: header
      name: Authorization

    CsrfToken:
      description: Put CSRF Token
      type: apiKey
      in: header
      name: X-CSRF-TOKEN

  responses:
    401:
      description: User Token Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WebResponse"
          example:
            data: null
            errors: Unauthorized
            paging: null
    403:
      description: CSRF Token not valid
      content:
        application/json:
          schema:
            type: object
            properties:
              timestamp:
                type: string
                example: 2024-02-09T13:10:51.107+00:00
              status:
                type: integer
                example: 403
              error:
                type: string
                example: Forbidden
              path:
                type: string
                example: /api/articles

  schemas:

    LoginAdminRequest:
      type: object
      properties:
        username:
          type: string
          required: true
          nullable: false
          example: mhmmdnaufal
        password:
          type: string
          required: true
          nullable: false
          example: rahasia

    CreateArticleRequest:
      required:
        - body
        - title
      type: object
      properties:
        title:
          maxLength: 100
          minLength: 0
          type: string
        coverImage:
          type: string
          format: binary
        body:
          maxLength: 65535
          minLength: 0
          type: string
        teaser:
          maxLength: 200
          minLength: 0
          type: string
        tags:
          uniqueItems: true
          type: array
          items:
            type: string
        images:
          type: array
          items:
            type: string
            format: binary

    UpdateArticleRequest:
      type: object
      required:
        - body
        - title
      properties:
        title:
          maxLength: 100
          minLength: 0
          type: string
          example: Ini Judul
        coverImage:
          type: string
          format: binary
          example: fyecy2ry43ycr3n9hfrhn9vnaofhafafp3]ptr432u9v8qq
        body:
          maxLength: 65535
          minLength: 0
          type: string
          example: Article merupakan karya tulis lengkap, misalnya laporan berita atau esai dalam majalah, surat kabar dan sebagainya
        teaser:
          maxLength: 200
          minLength: 0
          type: string
          example: Artikel ini membicarakan definisi artikel
        tags:
          type: array
          uniqueItems: true
          items:
            type: string
          example:
            - Article
            - Artikel
            - Definition
            - Karya Tulis
        images:
          type: array
          items:
            type: string
            format: binary
          example:
            - ufrun994832unr9asfjajfvjpjbpjf[jf]FFK0[fbk0aifpoi9-rinbt
            - aisodjoijnvur0-vUAVHFNH4392upfjFEJNP[RJPFEJSRa5ybqhww
            - ohjnf08u4n0t4u30rajfvapjevjeqjtqjbatq4t632tq4wt4tn
            - 5923ybn9yahbtoghosdhgoabjtogj502ajvfjojnbjj09ut

    OnlyArticleResponse:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        body:
          type: string
        teaser:
          type: string
        coverImage:
          type: array
          items:
            type: string
            format: byte

    RegisterAdminRequest:
      type: object
      required:
        - username
        - password
        - name
      properties:
        username:
          maxLength: 20
          minLength: 1
          type: string
        password:
          maxLength: 50
          minLength: 8
          type: string
        name:
          maxLength: 100
          minLength: 1
          type: string
        image:
          type: string
          format: binary

    WebResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        errors:
          type: string
          nullable: true
        paging:
          $ref: "#/components/schemas/PagingResponse"

    PagingResponse:
      type: object
      nullable: true
      properties:
        currentPage:
          type: integer
          format: int32
        totalPage:
          type: integer
          format: int32
        size:
          type: integer
          format: int32

    WebResponseListOnlyArticleResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/OnlyArticleResponse"
        errors:
          type: string
        paging:
          $ref: "#/components/schemas/PagingResponse"

    WebResponseString:
      type: object
      properties:
        data:
          type: string
        errors:
          type: string
        paging:
          $ref: '#/components/schemas/PagingResponse'

    WebResponseArticleResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
            body:
              type: string
            teaser:
              type: string
            tags:
              uniqueItems: true
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
            admin:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                image:
                  type: array
                  items:
                    type: string
                    format: byte
            coverImage:
              type: array
              items:
                type: string
                format: byte
            images:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  image:
                    type: array
                    items:
                      type: string
                      format: byte
        errors:
          type: string
        paging:
          $ref: '#/components/schemas/PagingResponse'
